name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Kiểm tra danh sách file
        run: ls -R # Lệnh này để xem bạn đã up file đúng chỗ chưa

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Cordova & Build
        run: |
          npm install -g cordova
          cordova create demo com.vector.gl2 VectorApp
          # Chép toàn bộ file của bạn vào thư mục build
          cp -r * demo/www/ 
          cd demo
          cordova platform add android
          cordova build android --release
