name: Build APK Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova App
        run: |
          cordova create myApp com.engine.app EngineApp
          rm -rf myApp/www/*
          cp -r *.js index.html config.xml myApp/www/
          cd myApp
          cordova platform add android
          cordova build android

      - name: Find APK
        run: |
          find myApp -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Engine-APK
          path: myApp/**/*.apk
