name: Build APK Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create and build app
        run: |
          cordova create myApp com.vector.gl2 VectorGL2
          cp index.html main.js constants.js config.xml myApp/www/
          cd myApp
          cordova platform add android
          cordova build android --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: myApp/platforms/android/app/build/outputs/apk/release/*.apk
